# Generated by Django 2.0.3 on 2020-04-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pasta_platter_salad_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasta',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='platter',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='created_at',
        ),
    ]
