# Generated by Django 2.0.3 on 2020-04-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200401_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='extras',
            field=models.ManyToManyField(blank=True, null=True, to='orders.Topping'),
        ),
    ]
