# Generated by Django 2.0.3 on 2020-04-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200401_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='size',
            field=models.CharField(default='Small', max_length=5),
        ),
        migrations.AlterField(
            model_name='sub',
            name='extras',
            field=models.ManyToManyField(blank=True, to='orders.Topping'),
        ),
    ]
