# Generated by Django 2.0.3 on 2020-04-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200401_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='size',
            field=models.CharField(max_length=5),
        ),
    ]
